# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Check docker compose v1 version
        run: docker-compose --version

      - name: Check docker compose v2 version
        run: docker compose version
        
      - name: Check entropy
        run: cat /proc/sys/kernel/random/entropy_avail
        
      - name: Install haveged
        run: |
          sudo apt -y install haveged
          sleep 5

      - name: Check entropy again
        run: cat /proc/sys/kernel/random/entropy_avail

